### ISSUE TITLE
Error al enviar una orden al mercado

### ISSUE THREAD

**Issue by csozac** [daplay/jsurbtc#3]
No se puede enviar orden al mercado.

Orden a enviar: 
JSurbtc.newOrder("ETH-CLP", "Bid", "limit", BigDecimal.valueOf(0.00010), BigDecimal.valueOf(651751.0));

Adjunto detalle del error:

cl.daplay.jsurbtc.model.JSurbtcException: Surbtc request failed. http status code: 422,
 message: 'Validation Failed',
 code: 'invalid_record'
	at cl.daplay.jsurbtc.jackson.JacksonJSON.error2Error(JacksonJSON.java:168)
	at cl.daplay.jsurbtc.jackson.JacksonJSON.exception(JacksonJSON.java:157)
	at cl.daplay.jsurbtc.JSurbtc.lambda$responseHandler$2(JSurbtc.java:255)
	at cl.daplay.jsurbtc.http.DefaultHTTPClient.doRequest(DefaultHTTPClient.java:113)
	at cl.daplay.jsurbtc.http.DefaultHTTPClient.post(DefaultHTTPClient.java:48)
	at cl.daplay.jsurbtc.http.RetryHTTPClient.lambda$post$2(RetryHTTPClient.java:32)
	at cl.daplay.jsurbtc.http.RetryHTTPClient.retry(RetryHTTPClient.java:47)
	at cl.daplay.jsurbtc.http.RetryHTTPClient.post(RetryHTTPClient.java:32)
	at cl.daplay.jsurbtc.JSurbtc.newOrder(JSurbtc.java:117)

**Comment by daniel-baez** [comment]
@csozac I improved the output for errors https://github.com/daplay/jsurbtc/commit/1b1636a0f14e20f50e86cd3c58442ab9fa8090a6 let me know how it goes
